- name: checking process of pm2 client_side
  become: yes
  shell: pm2 id dashboard
  register: pm2_output
  tags: install

- name: checking the existing pm2 processes if running
  shell: pm2 delete dashboard
  when: pm2_output.stdout != "[]"
  ignore_errors: True
  become: yes
  tags: install

- name: Starting the http-server
  become: yes
  shell: pm2 start /usr/bin/http-server --name dashboard -- -d false -a {{ local_ipv4_address }} -p 4200 
  args:
    chdir: "{{ base_dir }}/cqube/reference-visualization-app/dashboard/dist/ncert"
  tags: install
