---
- name: Creating the auth-api Directory for the installation
  file:
    path: "{{ base_dir }}/cqube/apis/auth-api"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    recurse: yes
    state: directory
  tags: [ install, update ]

- name: copying auth script
  copy:
    src: "../../authentication/keycloak-login-api/"
    dest: "{{base_dir}}/cqube/apis/auth-api"
  tags: [ install, update ]

- name: NodeJS dependencies install
  npm:
    path: "{{base_dir}}/cqube/apis/auth-api"
  tags: [ install, update ]

- name: Creating environmental variables
  file:
    path: "{{base_dir}}/cqube/apis/auth-api/.env"
    state: touch
    mode: u+rw,g+rw,o+rw
  tags: [ install, update ]

- name: Loading required data inside .env file
  blockinfile:
    path: "{{base_dir}}/cqube/apis/auth-api/.env"
    block: |
      KEYCLOAK_HOST = "{{ protocol }}://{{ api_endpoint }}"
      KEYCLOAK_REALM = "{{ realm_name }}"
      KEYCLOAK_CLIENT = "{{ angular_app_client_id }}"
         
      KEYCLOAK_USER= "{{ keycloak_adm_user }}"
      PASSWORD= "{{ keycloak_adm_passwd }}"
      GRANT_TYPE= "password"
  tags: [ install, update ]
