---
- name: Upgrading cQube
  hosts: localhost
  gather_facts: true
  remote_user: root
  vars_files:
    - ../config.yml  
    - ../memory_config.yml 
    - ../.version
    
  roles: 
          - postgres
          - python_flask
          - { role: kong, tags: update }
          - keycloak
          - prometheus
          - nifi_install
          - angular
          - cqube_version
