---
- name: checking process of pm2 admin_server_side
  become: yes
  shell: pm2 id admin-api
  register: pm2_output
  tags: install

- name: checking the existing pm2 processes if running
  shell: pm2 delete admin-api
  when: pm2_output.stdout != "[]"
  ignore_errors: True
  become: yes
  tags: install

- name: Starting NodeJS application
  become: yes
  shell: pm2 start npm --name admin-api -- start
  args:
    chdir: "{{ base_dir }}/cqube/apis/admin-api"
  notify: 
    - restart keycloak
  tags: install

- name: Starting the admin_server_side app
  become: yes
  shell: pm2 start admin-api
  notify: 
    - restart keycloak
  tags: update
