---
- name: checking process of pm2 admin_http_server
  become: yes
  shell: pm2 id admin-dashboard
  register: pm2_output
  tags: install

- name: checking the existing pm2 processes if running
  shell: pm2 delete admin-dashboard
  when: pm2_output.stdout != "[]"
  ignore_errors: True
  become: yes
  tags: install

- name: Starting / restarting the http-server
  become: yes
  shell: pm2 start /usr/bin/http-server --name admin-dashboard -- -d false -a {{ local_ipv4_address }} -p 4201 --gzip
  args:
    chdir: "{{ base_dir }}/cqube/reference-visualization-app/admin-console/dist"
  tags: install

- name: Starting the admin_client_side app
  become: yes
  shell: pm2 start admin-dashboard -- -d false -a {{ local_ipv4_address }} -p 4201
  tags: update
